[Change] Lock the `stripTranslationColors` option on MC 1.1 and below
- Found to be the root cause of the following issues:

- [MOJANG BUG] Insufficient Text Color support on 1.1 and lower
- [MOJANG BUG] OutOfRange String issues on b1.2_02 and lower (Doesn't effect NSSS)
  - Stacktrace:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 46
	at java.lang.String.charAt(String.java:658)
	at nh.a(nh.java:150)
	at nh.a(nh.java:117)
	at com.gitlab.cdagaming.craftpresence.utils.gui.integrations.ExtendedScreen.renderString(ExtendedScreen.java:735)
	at com.gitlab.cdagaming.craftpresence.utils.gui.widgets.TextDisplayWidget.draw(TextDisplayWidget.java:162)
	at com.gitlab.cdagaming.craftpresence.utils.gui.integrations.ExtendedScreen.preRender(ExtendedScreen.java:341)
	at com.gitlab.cdagaming.craftpresence.utils.gui.integrations.ExtendedScreen.a(ExtendedScreen.java:384)
	at com.gitlab.cdagaming.craftpresence.utils.gui.integrations.ExtendedScreen.a(ExtendedScreen.java:411)
	at ll.b(SourceFile:360)
	at net.minecraft.client.Minecraft.run(SourceFile:668)
	at java.lang.Thread.run(Thread.java:750)
```

The option is now disabled by default in new configs, but similar to the `guiBackgroundColor` and `buttonBackgroundColor` properties, there is no migration layer for this, due to their configurability.

I may change this in later updates, but we'll see.